# Generated by Django 5.2.16 on 2026-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='折扣率'),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价'),
        ),
    ]
