# Generated by Django 5.2.16 on 2026-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_checked_in_booking_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费'),
        ),
        migrations.AddField(
            model_name='booking',
            name='occupancy_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='占用唯一键'),
        ),
    ]
