# Generated by Django 5.2.16 on 2026-08-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_nickname_and_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='拉黑'),
        ),
    ]
