# Generated by Django 5.2.16 on 2026-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_blacklisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('normal', '普通会员'), ('silver', '银卡会员'), ('gold', '金卡会员')], default='normal', max_length=20, verbose_name='会员等级'),
        ),
    ]
