# Generated by Django 5.2.16 on 2026-07-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='场馆名称')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '场馆',
                'verbose_name_plural': '场馆',
                'db_table': 'venues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='venues.venue', verbose_name='所属场馆')),
            ],
            options={
                'verbose_name': '时段',
                'verbose_name_plural': '时段',
                'db_table': 'time_slots',
                'ordering': ['venue', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'start_time', 'end_time'), name='uq_venue_slot_time')],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='场地名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='venues.venue', verbose_name='所属场馆')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
                'db_table': 'courts',
                'ordering': ['venue', 'name'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'name'), name='uq_venue_court_name')],
            },
        ),
    ]
