# Generated by Django 5.2.16 on 2026-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('recharge', '充值'), ('booking', '消费'), ('refund', '退款')], default='booking', max_length=20, verbose_name='类型'),
        ),
    ]
