# Generated by Django 5.2.16 on 2026-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='赠送金额'),
        ),
    ]
