# Generated by Django 5.2.16 on 2026-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('balance', '余额支付'), ('wechat', '微信支付'), ('alipay', '支付宝'), ('cash', '现金')], default='balance', max_length=20, verbose_name='支付方式'),
        ),
    ]
